# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 787a7f3aa98ea2c7263f22a900e3f3bea3820dd5059c7ef8e15c6b019016d9eaebed869c9f357393239b52fcbe19afc1982d0c834317de28c42e43b783c6d4ac

test:
  secret_key_base: 42ff612a3e61ba476978c321ad23478e830bd1e9393ec75c57b098b57e0198faae54336f67e4fbce92b8dda0d065285130db817fd29f454f05e898341e50366c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
